export default {
  products: [
    {
      _id: "111111111111111111111111",
      name: "Camisa m. Hiskywin",
      tag: "#Camisas, #Roupa feminina, #Vestuário de verão",
      image: "../assets/products/product-01.jpg",
      imageAlt: "../assets/products/product-01-alt.jpg",
      price: 52.99,
      color: "Branco",
      brand: "Hiskywin",
      rating: 2.5,
      countStock: 10,
      description: `Fusce a massa quis purus lobortis rutrum ac et sapien. Nunc sit amet elit a magna condimentum gravida. Quisque laoreet sollicitudin suscipit. Fusce ante orci, ultricies eget ultricies faucibus, vulputate eget justo. Maecenas vel ipsum faucibus, ullamcorper sem sit amet, pulvinar justo. Proin sit amet pellentesque felis. Donec aliquet leo neque, faucibus pellentesque velit blandit id. Mauris suscipit libero sed sapien iaculis rhoncus. Fusce sagittis ultrices nibh, eu sollicitudin nulla dignissim sodales. In vel lorem ut turpis semper suscipit id sed nisl.`,
    },
    {
      _id: "222222222222222222222222",
      name: "Camisa m. Innerbloom",
      tag: "#Camisas, #Roupa feminina, #Vestuário de verão",
      image: "../assets/products/product-02.jpg",
      imageAlt: "../assets/products/product-02-alt.jpg",
      price: 44.99,
      color: "Azul claro",
      brand: "Innerbloom",
      rating: 3.0,
      countStock: 6,
      description: `Fusce a massa quis purus lobortis rutrum ac et sapien. Nunc sit amet elit a magna condimentum gravida. Quisque laoreet sollicitudin suscipit. Fusce ante orci, ultricies eget ultricies faucibus, vulputate eget justo. Maecenas vel ipsum faucibus, ullamcorper sem sit amet, pulvinar justo. Proin sit amet pellentesque felis. Donec aliquet leo neque, faucibus pellentesque velit blandit id. Mauris suscipit libero sed sapien iaculis rhoncus. Fusce sagittis ultrices nibh, eu sollicitudin nulla dignissim sodales. In vel lorem ut turpis semper suscipit id sed nisl.`,
    },
    {
      _id: "333333333333333333333333",
      name: "Camisa m. longa Zapda",
      tag: "#Camisas, #Roupa feminina, #Vestuário de verão",
      image: "../assets/products/product-03.jpg",
      imageAlt: "../assets/products/product-03-alt.jpg",
      price: 54.99,
      color: "Amarelo",
      brand: "Zapda",
      rating: 3.5,
      countStock: 5,
      description: `Fusce a massa quis purus lobortis rutrum ac et sapien. Nunc sit amet elit a magna condimentum gravida. Quisque laoreet sollicitudin suscipit. Fusce ante orci, ultricies eget ultricies faucibus, vulputate eget justo. Maecenas vel ipsum faucibus, ullamcorper sem sit amet, pulvinar justo. Proin sit amet pellentesque felis. Donec aliquet leo neque, faucibus pellentesque velit blandit id. Mauris suscipit libero sed sapien iaculis rhoncus. Fusce sagittis ultrices nibh, eu sollicitudin nulla dignissim sodales. In vel lorem ut turpis semper suscipit id sed nisl.`,
    },
    {
      _id: "444444444444444444444444",
      name: "Camisa m. longa Daltex",
      tag: "#Camisas, #Roupa feminina, #Vestuário de verão",
      image: "../assets/products/product-04.jpg",
      imageAlt: "../assets/products/product-04-alt.jpg",
      price: 38.99,
      color: "Rosa claro",
      brand: "Daltex",
      rating: 4.5,
      countStock: 8,
      description: `Fusce a massa quis purus lobortis rutrum ac et sapien. Nunc sit amet elit a magna condimentum gravida. Quisque laoreet sollicitudin suscipit. Fusce ante orci, ultricies eget ultricies faucibus, vulputate eget justo. Maecenas vel ipsum faucibus, ullamcorper sem sit amet, pulvinar justo. Proin sit amet pellentesque felis. Donec aliquet leo neque, faucibus pellentesque velit blandit id. Mauris suscipit libero sed sapien iaculis rhoncus. Fusce sagittis ultrices nibh, eu sollicitudin nulla dignissim sodales. In vel lorem ut turpis semper suscipit id sed nisl.`,
    },
    {
      _id: "555555555555555555555555",
      name: "Camisa m. longa Dentoex",
      tag: "#Camisas, #Roupa feminina, #Vestuário de verão",
      image: "../assets/products/product-05.jpg",
      imageAlt: "../assets/products/product-05-alt.jpg",
      price: 54.99,
      color: "Verde",
      brand: "Dentoex",
      rating: 3.0,
      countStock: 3,
      description: `Fusce a massa quis purus lobortis rutrum ac et sapien. Nunc sit amet elit a magna condimentum gravida. Quisque laoreet sollicitudin suscipit. Fusce ante orci, ultricies eget ultricies faucibus, vulputate eget justo. Maecenas vel ipsum faucibus, ullamcorper sem sit amet, pulvinar justo. Proin sit amet pellentesque felis. Donec aliquet leo neque, faucibus pellentesque velit blandit id. Mauris suscipit libero sed sapien iaculis rhoncus. Fusce sagittis ultrices nibh, eu sollicitudin nulla dignissim sodales. In vel lorem ut turpis semper suscipit id sed nisl.`,
    },
    {
      _id: "666666666666666666666666",
      name: "Camisa m. longa Newity",
      tag: "#Camisas, #Roupa feminina, #Vestuário de verão",
      image: "../assets/products/product-06.jpg",
      imageAlt: "../assets/products/product-06-alt.jpg",
      price: 46.99,
      color: "Branco",
      brand: "Newity",
      rating: 4.1,
      countStock: 4,
      description: `Fusce a massa quis purus lobortis rutrum ac et sapien. Nunc sit amet elit a magna condimentum gravida. Quisque laoreet sollicitudin suscipit. Fusce ante orci, ultricies eget ultricies faucibus, vulputate eget justo. Maecenas vel ipsum faucibus, ullamcorper sem sit amet, pulvinar justo. Proin sit amet pellentesque felis. Donec aliquet leo neque, faucibus pellentesque velit blandit id. Mauris suscipit libero sed sapien iaculis rhoncus. Fusce sagittis ultrices nibh, eu sollicitudin nulla dignissim sodales. In vel lorem ut turpis semper suscipit id sed nisl.`,
    },
    {
      _id: "777777777777777777777777",
      name: "Blusa Dentotam",
      tag: "#Blusas, #Roupa feminina, #Vestuário de verão",
      image: "../assets/products/product-07.jpg",
      imageAlt: "../assets/products/product-07-alt.jpg",
      price: 64.99,
      color: "Vermelho",
      brand: "Dentotam",
      rating: 4.0,
      countStock: 7,
      description: `Fusce a massa quis purus lobortis rutrum ac et sapien. Nunc sit amet elit a magna condimentum gravida. Quisque laoreet sollicitudin suscipit. Fusce ante orci, ultricies eget ultricies faucibus, vulputate eget justo. Maecenas vel ipsum faucibus, ullamcorper sem sit amet, pulvinar justo. Proin sit amet pellentesque felis. Donec aliquet leo neque, faucibus pellentesque velit blandit id. Mauris suscipit libero sed sapien iaculis rhoncus. Fusce sagittis ultrices nibh, eu sollicitudin nulla dignissim sodales. In vel lorem ut turpis semper suscipit id sed nisl.`,
    },

    {
      _id: "888888888888888888888888",
      name: "Camisa m. longa Fixair",
      tag: "#Camisas, #Roupa feminina, #Vestuário de verão",
      image: "../assets/products/product-09.jpg",
      imageAlt: "../assets/products/product-09-alt.jpg",
      price: 69.99,
      color: "Laurel",
      brand: "Fixair",
      rating: 4.5,
      countStock: 13,
      description: `Fusce a massa quis purus lobortis rutrum ac et sapien. Nunc sit amet elit a magna condimentum gravida. Quisque laoreet sollicitudin suscipit. Fusce ante orci, ultricies eget ultricies faucibus, vulputate eget justo. Maecenas vel ipsum faucibus, ullamcorper sem sit amet, pulvinar justo. Proin sit amet pellentesque felis. Donec aliquet leo neque, faucibus pellentesque velit blandit id. Mauris suscipit libero sed sapien iaculis rhoncus. Fusce sagittis ultrices nibh, eu sollicitudin nulla dignissim sodales. In vel lorem ut turpis semper suscipit id sed nisl.`,
    },
    {
      _id: "999999999999999999999999",
      name: "Camisa m. longa Lexywarm",
      tag: "#Blusas, #Roupa feminina, #Vestuário de verão",
      image: "../assets/products/product-10.jpg",
      imageAlt: "../assets/products/product-10-alt.jpg",
      price: 66.99,
      color: "Preto",
      brand: "Lexywarm",
      rating: 3.8,
      countStock: 9,
      description: `Fusce a massa quis purus lobortis rutrum ac et sapien. Nunc sit amet elit a magna condimentum gravida. Quisque laoreet sollicitudin suscipit. Fusce ante orci, ultricies eget ultricies faucibus, vulputate eget justo. Maecenas vel ipsum faucibus, ullamcorper sem sit amet, pulvinar justo. Proin sit amet pellentesque felis. Donec aliquet leo neque, faucibus pellentesque velit blandit id. Mauris suscipit libero sed sapien iaculis rhoncus. Fusce sagittis ultrices nibh, eu sollicitudin nulla dignissim sodales. In vel lorem ut turpis semper suscipit id sed nisl.`,
    },

    {
      _id: "101010101010101010101010",
      name: "Blusa Emotion",
      tag: "#Blusas, #Roupa feminina, #Vestuário de verão",
      image: "../assets/products/product-12.jpg",
      imageAlt: "../assets/products/product-12-alt.jpg",
      price: 82.99,
      color: "Crocodile",
      brand: "Emotion",
      rating: 3.2,
      countStock: 5,
      description: `Fusce a massa quis purus lobortis rutrum ac et sapien. Nunc sit amet elit a magna condimentum gravida. Quisque laoreet sollicitudin suscipit. Fusce ante orci, ultricies eget ultricies faucibus, vulputate eget justo. Maecenas vel ipsum faucibus, ullamcorper sem sit amet, pulvinar justo. Proin sit amet pellentesque felis. Donec aliquet leo neque, faucibus pellentesque velit blandit id. Mauris suscipit libero sed sapien iaculis rhoncus. Fusce sagittis ultrices nibh, eu sollicitudin nulla dignissim sodales. In vel lorem ut turpis semper suscipit id sed nisl.`,
    },
    {
      _id: "121212121212121212121212",
      name: "Regata Donkix",
      tag: "#Regatas, #Roupa feminina, #Vestuário de verão",
      image: "../assets/products/product-13.jpg",
      imageAlt: "../assets/products/product-13-alt.jpg",
      price: 57.99,
      color: "Cinza",
      brand: "Donkix",
      rating: 4.8,
      countStock: 7,
      description: `Fusce a massa quis purus lobortis rutrum ac et sapien. Nunc sit amet elit a magna condimentum gravida. Quisque laoreet sollicitudin suscipit. Fusce ante orci, ultricies eget ultricies faucibus, vulputate eget justo. Maecenas vel ipsum faucibus, ullamcorper sem sit amet, pulvinar justo. Proin sit amet pellentesque felis. Donec aliquet leo neque, faucibus pellentesque velit blandit id. Mauris suscipit libero sed sapien iaculis rhoncus. Fusce sagittis ultrices nibh, eu sollicitudin nulla dignissim sodales. In vel lorem ut turpis semper suscipit id sed nisl.`,
    },

    {
      _id: "131313131313131313131313",
      name: "Blusa m. longa Sensation",
      tag: "#Blusas, #Roupa feminina, #Vestuário de inverno",
      image: "../assets/products/product-15.jpg",
      imageAlt: "../assets/products/product-15-alt.jpg",
      price: 64.99,
      color: "Preto",
      brand: "Sensation",
      rating: 4.4,
      countStock: 7,
      description: `Fusce a massa quis purus lobortis rutrum ac et sapien. Nunc sit amet elit a magna condimentum gravida. Quisque laoreet sollicitudin suscipit. Fusce ante orci, ultricies eget ultricies faucibus, vulputate eget justo. Maecenas vel ipsum faucibus, ullamcorper sem sit amet, pulvinar justo. Proin sit amet pellentesque felis. Donec aliquet leo neque, faucibus pellentesque velit blandit id. Mauris suscipit libero sed sapien iaculis rhoncus. Fusce sagittis ultrices nibh, eu sollicitudin nulla dignissim sodales. In vel lorem ut turpis semper suscipit id sed nisl.`,
    },
    {
      _id: "141414141414141414141414",
      name: "Camisa m. longa Faxttex",
      tag: "#Blusas, #Roupa feminina, #Vestuário de inverno",
      image: "../assets/products/product-11.jpg",
      imageAlt: "../assets/products/product-11-alt.jpg",
      price: 58.99,
      color: "Ice blue",
      brand: "Faxttex",
      rating: 3.7,
      countStock: 2,
      description: `Fusce a massa quis purus lobortis rutrum ac et sapien. Nunc sit amet elit a magna condimentum gravida. Quisque laoreet sollicitudin suscipit. Fusce ante orci, ultricies eget ultricies faucibus, vulputate eget justo. Maecenas vel ipsum faucibus, ullamcorper sem sit amet, pulvinar justo. Proin sit amet pellentesque felis. Donec aliquet leo neque, faucibus pellentesque velit blandit id. Mauris suscipit libero sed sapien iaculis rhoncus. Fusce sagittis ultrices nibh, eu sollicitudin nulla dignissim sodales. In vel lorem ut turpis semper suscipit id sed nisl.`,
    },
    {
      _id: "151515151515151515151515",
      name: "Blusa m. longa Anorak",
      tag: "#Blusas, #Roupa feminina, #Vestuário de inverno",
      image: "../assets/products/product-14.jpg",
      imageAlt: "../assets/products/product-14-alt.jpg",
      price: 52.99,
      color: "Cinza escuro",
      brand: "Anorak",
      rating: 3.5,
      countStock: 2,
      description: `Fusce a massa quis purus lobortis rutrum ac et sapien. Nunc sit amet elit a magna condimentum gravida. Quisque laoreet sollicitudin suscipit. Fusce ante orci, ultricies eget ultricies faucibus, vulputate eget justo. Maecenas vel ipsum faucibus, ullamcorper sem sit amet, pulvinar justo. Proin sit amet pellentesque felis. Donec aliquet leo neque, faucibus pellentesque velit blandit id. Mauris suscipit libero sed sapien iaculis rhoncus. Fusce sagittis ultrices nibh, eu sollicitudin nulla dignissim sodales. In vel lorem ut turpis semper suscipit id sed nisl.`,
    },
    {
      _id: "161616161616161616161616",
      name: "Blusa Lexizimin",
      tag: "#Blusas, #Roupa feminina, #Vestuário de verão",
      image: "../assets/products/product-08.jpg",
      imageAlt: "../assets/products/product-08-alt.jpg",
      price: 32.99,
      color: "Papaya",
      brand: "Lexizimin",
      rating: 5.5,
      countStock: 7,
      description: `Fusce a massa quis purus lobortis rutrum ac et sapien. Nunc sit amet elit a magna condimentum gravida. Quisque laoreet sollicitudin suscipit. Fusce ante orci, ultricies eget ultricies faucibus, vulputate eget justo. Maecenas vel ipsum faucibus, ullamcorper sem sit amet, pulvinar justo. Proin sit amet pellentesque felis. Donec aliquet leo neque, faucibus pellentesque velit blandit id. Mauris suscipit libero sed sapien iaculis rhoncus. Fusce sagittis ultrices nibh, eu sollicitudin nulla dignissim sodales. In vel lorem ut turpis semper suscipit id sed nisl.`,
    },
  ],
};
